/**
 * resources — definición de las secciones CRUD del panel (una sola fuente para servidor y panel).
 *
 * Cada recurso: { key, table, perm (módulo de permisos), group (menú), label, labelSql (texto en selects),
 *   fields: [{ name, label, type, required, options, ref, list, readonly, default, help }],
 *   search: columnas buscables, sort: orden por defecto, ops: operaciones permitidas, filters }
 *
 * Tipos de campo: text · textarea · number · money · percent · bool · select · ref · image · file · date ·
 *   datetime · json · color · email · phone · password · readonly · polygon · owner · permissions
 * `list: true` → columna en la tabla del listado. Las etiquetas están en español (traducibles en el panel).
 */
const opt = (...pairs) => pairs.map(([value, label]) => ({ value, label }));

const STATUS_ACTIVE = opt(['active', 'Activo'], ['blocked', 'Bloqueado']);
const BOOKING_STATUS = opt(['awaiting_payment', 'Esperando pago con tarjeta'], ['searching', 'Buscando conductor'], ['accepted', 'Aceptado'],
  ['arrived', 'Conductor en el punto'], ['started', 'En curso'], ['completed', 'Completado'], ['cancelled', 'Cancelado'], ['expired', 'Caducado']);
const PAY_METHOD = opt(['cash', 'Efectivo'], ['wallet', 'Monedero'], ['stripe', 'Tarjeta de crédito']);
const PAY_STATUS = opt(['pending', 'Pendiente'], ['authorized', 'Reservado en la tarjeta'], ['paid', 'Pagado'], ['failed', 'Fallido'],
  ['released', 'Reserva liberada'], ['refunded', 'Reembolsado']);
const AUDIENCE = opt(['customer', 'Clientes'], ['driver', 'Conductores'], ['all', 'Todos']);
const PRIORITY = opt(['low', 'Baja'], ['normal', 'Normal'], ['high', 'Alta'], ['urgent', 'Urgente']);
const OWNER = opt(['customer', 'Cliente'], ['driver', 'Conductor']);

const R = [
  // ── Operación ──────────────────────────────────────────────────────────────
  { key: 'bookings', table: 'bookings', perm: 'booking', group: 'Operación', label: 'Reservas', icon: '🚕',
    labelSql: 'code', search: ['code', 'pickup_address', 'dropoff_address'], sort: 'created_at DESC', ops: ['view', 'edit', 'delete'],
    filters: ['status', 'payment_status', 'city_id'],
    fields: [
      { name: 'code', label: 'Código', type: 'readonly', list: true },
      { name: 'customer_id', label: 'Cliente', type: 'ref', ref: 'customers', readonly: true, list: true },
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', list: true },
      { name: 'ride_type_id', label: 'Tipo de viaje', type: 'ref', ref: 'ride_types', readonly: true, list: true },
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities', readonly: true },
      { name: 'pickup_address', label: 'Recogida', type: 'readonly', list: true },
      { name: 'dropoff_address', label: 'Destino', type: 'readonly', list: true },
      { name: 'distance_km', label: 'Distancia (km)', type: 'readonly' },
      { name: 'duration_min', label: 'Duración (min)', type: 'readonly' },
      { name: 'estimated_fare', label: 'Precio estimado', type: 'readonly' },
      { name: 'total_amount', label: 'Importe total', type: 'money', list: true },
      { name: 'commission_amount', label: 'Comisión', type: 'readonly' },
      { name: 'driver_earning', label: 'Ganancia conductor', type: 'readonly' },
      { name: 'payment_method', label: 'Pago', type: 'select', options: PAY_METHOD },
      { name: 'payment_status', label: 'Estado del pago', type: 'select', options: PAY_STATUS, list: true },
      { name: 'status', label: 'Estado', type: 'select', options: BOOKING_STATUS, list: true },
      { name: 'cancel_reason', label: 'Motivo de cancelación', type: 'textarea' },
      { name: 'created_at', label: 'Creada', type: 'datetime', readonly: true, list: true },
    ] },

  // ── Geografía y tarifas ────────────────────────────────────────────────────
  { key: 'countries', table: 'countries', perm: 'country', group: 'Geografía', label: 'Países', icon: '🌍',
    labelSql: 'name', search: ['name', 'code'], sort: 'sort_order, name',
    fields: [
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'code', label: 'Código ISO', type: 'text', required: true, list: true, help: 'ES, GB, US…' },
      { name: 'currency_code', label: 'Moneda', type: 'text', required: true, list: true },
      { name: 'currency_symbol', label: 'Símbolo', type: 'text', required: true, list: true },
      { name: 'phone_code', label: 'Prefijo', type: 'text' },
      { name: 'default_language', label: 'Idioma', type: 'ref', ref: 'languages', refKey: 'code' },
      { name: 'lat', label: 'Latitud (centro)', type: 'number' }, { name: 'lng', label: 'Longitud (centro)', type: 'number' },
      { name: 'zoom', label: 'Zoom del mapa', type: 'number', default: 5 },
      { name: 'is_default', label: 'País por defecto', type: 'bool', list: true },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0 },
    ] },
  { key: 'cities', table: 'cities', perm: 'city', group: 'Geografía', label: 'Ciudades', icon: '🏙️',
    labelSql: 'name', search: ['name', 'state'], sort: 'name', filters: ['country_id', 'active'],
    fields: [
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'state', label: 'Provincia / estado', type: 'text', list: true },
      { name: 'country_id', label: 'País', type: 'ref', ref: 'countries', required: true, list: true },
      { name: 'lat', label: 'Latitud', type: 'number', required: true }, { name: 'lng', label: 'Longitud', type: 'number', required: true },
      { name: 'radius_km', label: 'Radio de servicio (km)', type: 'number', default: 30 },
      { name: 'timezone', label: 'Zona horaria', type: 'text', default: 'Europe/Madrid' },
      { name: 'active', label: 'Activa', type: 'bool', default: 1, list: true },
    ] },
  { key: 'zones', table: 'zones', perm: 'zone', group: 'Geografía', label: 'Zonas', icon: '🗺️',
    labelSql: 'name', search: ['name'], sort: 'name', filters: ['city_id'],
    fields: [
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities', required: true, list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'polygon', label: 'Área (polígono)', type: 'polygon', help: 'Dibuja la zona en el mapa' },
      { name: 'surge', label: 'Recargo actual (x)', type: 'number', default: 1, list: true },
      { name: 'weekly_slots', label: 'Franjas semanales de recargo', type: 'json', help: '[{"day":5,"from":"22:00","to":"23:59","surge":1.3}]' },
      { name: 'active', label: 'Activa', type: 'bool', default: 1, list: true },
    ] },
  { key: 'ride_types', table: 'ride_types', perm: 'ride_type', group: 'Tarifas', label: 'Tipos de viaje', icon: '🚗',
    labelSql: 'name', search: ['name', 'code'], sort: 'sort_order, name',
    fields: [
      { name: 'app_icon', label: 'Icono app', type: 'image', list: true },
      { name: 'map_icon', label: 'Icono mapa', type: 'image', list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'code', label: 'Código', type: 'text', required: true, list: true },
      { name: 'description', label: 'Descripción', type: 'text' },
      { name: 'city_id', label: 'Ciudad (vacío = todas)', type: 'ref', ref: 'cities' },
      { name: 'seats', label: 'Plazas', type: 'number', default: 4 },
      { name: 'base_price', label: 'Bajada de bandera', type: 'money', required: true, list: true },
      { name: 'price_per_km', label: 'Precio por km', type: 'money', required: true, list: true },
      { name: 'price_per_min', label: 'Precio por minuto', type: 'money' },
      { name: 'min_fare', label: 'Tarifa mínima', type: 'money' },
      { name: 'waiting_per_min', label: 'Espera por minuto', type: 'money' },
      { name: 'commission_rate', label: 'Comisión plataforma (%)', type: 'percent', default: 15, list: true },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0 },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
    ] },
  { key: 'cancellation_policies', table: 'cancellation_policies', perm: 'cancellation_policy', group: 'Tarifas', label: 'Políticas de cancelación', icon: '⛔',
    labelSql: 'name', search: ['name'],
    fields: [
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities', list: true },
      { name: 'ride_type_id', label: 'Tipo de viaje', type: 'ref', ref: 'ride_types', list: true },
      { name: 'applies_to', label: 'Se aplica a', type: 'select', options: OWNER, default: 'customer' },
      { name: 'free_window_min', label: 'Minutos gratis', type: 'number', default: 2, list: true },
      { name: 'fixed_fee', label: 'Cargo fijo', type: 'money', list: true },
      { name: 'fee_percent', label: 'Cargo (%)', type: 'percent', list: true },
      { name: 'active', label: 'Activa', type: 'bool', default: 1, list: true },
    ] },
  { key: 'city_taxes', table: 'city_taxes', perm: 'tax', group: 'Tarifas', label: 'Impuestos por ciudad', icon: '🧾',
    labelSql: 'name', search: ['name'],
    fields: [
      { name: 'city_id', label: 'Ciudad (vacío = todas)', type: 'ref', ref: 'cities', list: true },
      { name: 'name', label: 'Impuesto', type: 'text', required: true, list: true },
      { name: 'rate', label: 'Tipo (%)', type: 'percent', required: true, list: true },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
    ] },

  // ── Conductores ────────────────────────────────────────────────────────────
  { key: 'drivers', table: 'drivers', perm: 'drivers', group: 'Conductores', label: 'Conductores', icon: '🧑‍✈️',
    labelSql: 'name', search: ['name', 'phone', 'email'], sort: 'created_at DESC', ops: ['view', 'edit', 'delete'],
    filters: ['status', 'verified', 'online', 'city_id'],
    fields: [
      { name: 'photo', label: 'Foto', type: 'image', list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'phone', label: 'Teléfono', type: 'phone', list: true },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'country_id', label: 'País', type: 'ref', ref: 'countries' },
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['active', 'Activo'], ['blocked', 'Bloqueado']), list: true },
      { name: 'verified', label: 'Verificado', type: 'bool', list: true },
      { name: 'online', label: 'Conectado', type: 'bool', readonly: true, list: true },
      { name: 'available', label: 'Disponible', type: 'bool', readonly: true },
      { name: 'rating', label: 'Valoración', type: 'readonly', list: true },
      { name: 'debt', label: 'Deuda (comisiones de efectivo)', type: 'money', list: true },
      { name: 'referral_code', label: 'Código de invitación', type: 'readonly' },
      { name: 'created_at', label: 'Alta', type: 'datetime', readonly: true },
    ] },
  { key: 'vehicles', table: 'vehicles', perm: 'vehicles', group: 'Conductores', label: 'Vehículos', icon: '🚙',
    labelSql: "plate || ' · ' || coalesce(brand,'') || ' ' || coalesce(model,'')", search: ['plate', 'brand', 'model'], filters: ['status', 'ride_type_id'],
    fields: [
      { name: 'photo', label: 'Foto', type: 'image', list: true },
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', required: true, list: true },
      { name: 'ride_type_id', label: 'Tipo de viaje', type: 'ref', ref: 'ride_types', list: true },
      { name: 'plate', label: 'Matrícula', type: 'text', required: true, list: true },
      { name: 'brand', label: 'Marca', type: 'text', list: true }, { name: 'model', label: 'Modelo', type: 'text', list: true },
      { name: 'color', label: 'Color', type: 'text' }, { name: 'year', label: 'Año', type: 'number' },
      { name: 'seats', label: 'Plazas', type: 'number', default: 4 },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['active', 'Activo'], ['blocked', 'Bloqueado']), list: true },
    ] },
  { key: 'document_types', table: 'document_types', perm: 'document', group: 'Conductores', label: 'Tipos de documento', icon: '📄',
    labelSql: 'name', search: ['name'], sort: 'sort_order, name',
    fields: [
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'type', label: 'De', type: 'select', options: opt(['driver', 'Conductor'], ['vehicle', 'Vehículo']), list: true },
      { name: 'required', label: 'Obligatorio', type: 'bool', default: 1, list: true },
      { name: 'has_expiry', label: 'Tiene caducidad', type: 'bool', default: 1 },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0, list: true },
    ] },
  { key: 'driver_documents', table: 'driver_documents', perm: 'document', group: 'Conductores', label: 'Documentos de conductores', icon: '🗂️',
    labelSql: 'id', sort: 'created_at DESC', filters: ['status', 'document_type_id'],
    fields: [
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', required: true, list: true },
      { name: 'document_type_id', label: 'Documento', type: 'ref', ref: 'document_types', required: true, list: true },
      { name: 'file_url', label: 'Archivo', type: 'file', required: true, list: true },
      { name: 'number', label: 'Número', type: 'text' },
      { name: 'expires_at', label: 'Caduca', type: 'date', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['approved', 'Aprobado'], ['rejected', 'Rechazado']), list: true },
      { name: 'note', label: 'Nota', type: 'textarea' },
    ] },
  { key: 'driver_incentives', table: 'driver_incentives', perm: 'driver_incentive', group: 'Conductores', label: 'Incentivos', icon: '🏆',
    labelSql: 'title', search: ['title'],
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true, list: true },
      { name: 'description', label: 'Descripción', type: 'textarea' },
      { name: 'type', label: 'Tipo', type: 'select', options: opt(['rides', 'Nº de viajes'], ['earnings', 'Ganancias'], ['hours', 'Horas conectado']), list: true },
      { name: 'target', label: 'Objetivo', type: 'number', required: true },
      { name: 'reward', label: 'Premio', type: 'money', required: true, list: true },
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities' },
      { name: 'ride_type_id', label: 'Tipo de viaje', type: 'ref', ref: 'ride_types' },
      { name: 'start_time', label: 'Inicio', type: 'datetime', list: true }, { name: 'end_time', label: 'Fin', type: 'datetime', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['scheduled', 'Programado'], ['running', 'En curso'], ['finished', 'Terminado']), list: true },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
    ] },
  { key: 'withdrawal_requests', table: 'withdrawal_requests', perm: 'driver_payout', group: 'Conductores', label: 'Solicitudes de retirada', icon: '💸',
    labelSql: 'id', sort: 'created_at DESC', ops: ['view', 'edit', 'delete'], filters: ['status'],
    fields: [
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', readonly: true, list: true },
      { name: 'amount', label: 'Importe', type: 'readonly', list: true },
      { name: 'method', label: 'Método', type: 'readonly' },
      { name: 'account_details', label: 'Cuenta', type: 'readonly' },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['approved', 'Aprobada'], ['rejected', 'Rechazada'], ['paid', 'Pagada']), list: true },
      { name: 'note', label: 'Nota', type: 'textarea' },
      { name: 'created_at', label: 'Solicitada', type: 'datetime', readonly: true, list: true },
    ] },
  { key: 'cash_collection_points', table: 'cash_collection_points', perm: 'cash_point', group: 'Conductores', label: 'Puntos de cobro', icon: '🏪',
    labelSql: 'name', search: ['name', 'address'],
    fields: [
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities', list: true },
      { name: 'name', label: 'Punto de cobro', type: 'text', required: true, list: true },
      { name: 'address', label: 'Dirección', type: 'text', list: true },
      { name: 'lat', label: 'Latitud', type: 'number' }, { name: 'lng', label: 'Longitud', type: 'number' },
      { name: 'contact_person', label: 'Persona de contacto', type: 'text', list: true },
      { name: 'phone', label: 'Teléfono', type: 'phone', list: true },
      { name: 'opening_hours', label: 'Horario', type: 'text' },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
    ] },

  // ── Clientes ───────────────────────────────────────────────────────────────
  { key: 'customers', table: 'customers', perm: 'customers', group: 'Clientes', label: 'Clientes', icon: '🧍',
    labelSql: 'name', search: ['name', 'phone', 'email'], sort: 'created_at DESC', ops: ['view', 'edit', 'delete'], filters: ['status'],
    fields: [
      { name: 'photo', label: 'Foto', type: 'image', list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'email', label: 'Email', type: 'email', list: true },
      { name: 'phone', label: 'Teléfono', type: 'phone', list: true },
      { name: 'country_id', label: 'País', type: 'ref', ref: 'countries' },
      { name: 'status', label: 'Estado', type: 'select', options: STATUS_ACTIVE, list: true },
      { name: 'verified', label: 'Verificado', type: 'bool', list: true },
      { name: 'rating', label: 'Valoración', type: 'readonly' },
      { name: 'referral_code', label: 'Código de invitación', type: 'readonly' },
      { name: 'created_at', label: 'Alta', type: 'datetime', readonly: true },
    ] },
  { key: 'referral_bonuses', table: 'referral_bonuses', perm: 'referral_bonus', group: 'Clientes', label: 'Bonos de invitación', icon: '🎁',
    labelSql: 'id', sort: 'created_at DESC', filters: ['status'],
    fields: [
      { name: 'referrer_type', label: 'Invita (tipo)', type: 'select', options: OWNER, list: true },
      { name: 'referrer_id', label: 'Invita (id)', type: 'number', list: true },
      { name: 'referred_type', label: 'Invitado (tipo)', type: 'select', options: OWNER, list: true },
      { name: 'referred_id', label: 'Invitado (id)', type: 'number', list: true },
      { name: 'type', label: 'Bono para', type: 'select', options: opt(['referrer', 'Quien invita'], ['referred', 'Invitado']), list: true },
      { name: 'amount', label: 'Importe', type: 'money', required: true, list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['paid', 'Pagado'], ['cancelled', 'Cancelado']), list: true },
    ] },

  // ── Finanzas ───────────────────────────────────────────────────────────────
  { key: 'promo_codes', table: 'promo_codes', perm: 'promo_code', group: 'Finanzas', label: 'Códigos promocionales', icon: '🏷️',
    labelSql: 'code', search: ['code', 'description'], sort: 'created_at DESC',
    fields: [
      { name: 'code', label: 'Código', type: 'text', required: true, list: true },
      { name: 'description', label: 'Descripción', type: 'text' },
      { name: 'type', label: 'Tipo', type: 'select', options: opt(['percent', 'Porcentaje'], ['fixed', 'Importe fijo']), list: true },
      { name: 'value', label: 'Valor', type: 'number', required: true, list: true },
      { name: 'min_order', label: 'Pedido mínimo', type: 'money', list: true },
      { name: 'max_discount', label: 'Descuento máximo', type: 'money', list: true },
      { name: 'max_uses', label: 'Usos máximos (0 = ilimitado)', type: 'number', list: true },
      { name: 'used', label: 'Usos', type: 'readonly', list: true },
      { name: 'max_uses_per_user', label: 'Usos por cliente', type: 'number', default: 1, list: true },
      { name: 'city_id', label: 'Ciudad', type: 'ref', ref: 'cities' },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['active', 'Activo'], ['inactive', 'Inactivo']), list: true },
      { name: 'starts_at', label: 'Empieza', type: 'date', list: true }, { name: 'expires_at', label: 'Caduca', type: 'date', list: true },
    ] },
  { key: 'commissions', table: 'commissions', perm: 'commission', group: 'Finanzas', label: 'Comisiones', icon: '📊',
    labelSql: 'id', sort: 'created_at DESC', ops: ['view'],
    fields: [
      { name: 'booking_id', label: 'Reserva', type: 'ref', ref: 'bookings', list: true },
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', list: true },
      { name: 'service', label: 'Servicio', type: 'readonly', list: true },
      { name: 'fare', label: 'Tarifa', type: 'readonly', list: true },
      { name: 'commission', label: 'Comisión', type: 'readonly', list: true },
      { name: 'tax', label: 'Impuesto', type: 'readonly', list: true },
      { name: 'debt_amount', label: 'Deuda', type: 'readonly', list: true },
      { name: 'driver_earning', label: 'Ganancia conductor', type: 'readonly', list: true },
      { name: 'created_at', label: 'Fecha', type: 'datetime', readonly: true, list: true },
    ] },
  { key: 'invoices', table: 'invoices', perm: 'invoice', group: 'Finanzas', label: 'Facturas', icon: '🧾',
    labelSql: 'number', search: ['number'], sort: 'invoice_date DESC', ops: ['view'],
    fields: [
      { name: 'number', label: 'Factura nº', type: 'readonly', list: true },
      { name: 'customer_id', label: 'Cliente', type: 'ref', ref: 'customers', list: true },
      { name: 'driver_id', label: 'Conductor', type: 'ref', ref: 'drivers', list: true },
      { name: 'invoice_date', label: 'Fecha', type: 'datetime', list: true },
      { name: 'amount', label: 'Importe', type: 'readonly', list: true },
      { name: 'driver_amount', label: 'Conductor', type: 'readonly', list: true },
      { name: 'platform_commission', label: 'Comisión', type: 'readonly', list: true },
      { name: 'payment_method', label: 'Método', type: 'select', options: PAY_METHOD, list: true },
      { name: 'payment_status', label: 'Estado del pago', type: 'select', options: PAY_STATUS, list: true },
    ] },
  { key: 'wallets', table: 'wallets', perm: 'wallet', group: 'Finanzas', label: 'Monederos', icon: '👛',
    labelSql: "owner_type || ' #' || owner_id", sort: 'last_tx_at DESC', ops: ['view', 'edit'], filters: ['owner_type'],
    fields: [
      { name: 'owner_type', label: 'Tipo', type: 'select', options: OWNER, readonly: true, list: true },
      { name: 'owner_id', label: 'Titular', type: 'owner', readonly: true, list: true },
      { name: 'balance', label: 'Saldo', type: 'readonly', list: true },
      { name: 'credits', label: 'Abonos', type: 'readonly', list: true },
      { name: 'debits', label: 'Cargos', type: 'readonly', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: STATUS_ACTIVE, list: true },
      { name: 'last_tx_at', label: 'Último movimiento', type: 'datetime', readonly: true, list: true },
    ] },
  { key: 'wallet_transactions', table: 'wallet_transactions', perm: 'transaction', group: 'Finanzas', label: 'Movimientos de monedero', icon: '🔁',
    labelSql: 'id', sort: 'created_at DESC', ops: ['view'], filters: ['type'],
    fields: [
      { name: 'wallet_id', label: 'Monedero', type: 'ref', ref: 'wallets', list: true },
      { name: 'type', label: 'Tipo', type: 'select', options: opt(['credit', 'Abono'], ['debit', 'Cargo']), list: true },
      { name: 'amount', label: 'Importe', type: 'readonly', list: true },
      { name: 'balance_after', label: 'Saldo después', type: 'readonly', list: true },
      { name: 'description', label: 'Concepto', type: 'readonly', list: true },
      { name: 'status', label: 'Estado', type: 'readonly', list: true },
      { name: 'created_at', label: 'Fecha', type: 'datetime', readonly: true, list: true },
    ] },
  { key: 'refund_requests', table: 'refund_requests', perm: 'refund', group: 'Finanzas', label: 'Reembolsos', icon: '↩️',
    labelSql: 'id', sort: 'created_at DESC', ops: ['view', 'edit', 'delete'], filters: ['status'],
    fields: [
      { name: 'booking_id', label: 'Reserva', type: 'ref', ref: 'bookings', readonly: true, list: true },
      { name: 'customer_id', label: 'Cliente', type: 'ref', ref: 'customers', readonly: true, list: true },
      { name: 'reason', label: 'Motivo', type: 'readonly', list: true },
      { name: 'amount_requested', label: 'Solicitado', type: 'readonly', list: true },
      { name: 'amount_approved', label: 'Aprobado', type: 'money', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['pending', 'Pendiente'], ['approved', 'Aprobado'], ['rejected', 'Rechazado']), list: true },
      { name: 'source', label: 'Origen', type: 'readonly', list: true },
      { name: 'created_at', label: 'Solicitado', type: 'datetime', readonly: true, list: true },
    ] },

  // ── Soporte y contenido ────────────────────────────────────────────────────
  { key: 'support_tickets', table: 'support_tickets', perm: 'support_ticket', group: 'Soporte', label: 'Tickets de soporte', icon: '🎫',
    labelSql: 'number', search: ['number', 'subject'], sort: 'created_at DESC', ops: ['view', 'edit', 'delete'], filters: ['status', 'priority'],
    fields: [
      { name: 'number', label: 'Ticket nº', type: 'readonly', list: true },
      { name: 'owner_type', label: 'De', type: 'select', options: OWNER, readonly: true },
      { name: 'owner_id', label: 'Usuario', type: 'owner', readonly: true, list: true },
      { name: 'subject', label: 'Asunto', type: 'readonly', list: true },
      { name: 'category', label: 'Categoría', type: 'text', list: true },
      { name: 'status', label: 'Estado', type: 'select', options: opt(['open', 'Abierto'], ['pending', 'Pendiente'], ['closed', 'Cerrado']), list: true },
      { name: 'priority', label: 'Prioridad', type: 'select', options: PRIORITY, list: true },
      { name: 'assigned_to', label: 'Asignado a', type: 'ref', ref: 'admin_users', list: true },
      { name: 'last_reply_at', label: 'Última respuesta', type: 'datetime', readonly: true, list: true },
    ] },
  { key: 'banners', table: 'banners', perm: 'banner', group: 'Contenido', label: 'Banners', icon: '🖼️',
    labelSql: 'title', search: ['title'], sort: 'row, sort_order',
    fields: [
      { name: 'image_url', label: 'Imagen', type: 'image', required: true, list: true },
      { name: 'title', label: 'Título', type: 'text', list: true },
      { name: 'cities', label: 'Ciudades (vacío = todas)', type: 'json', list: true },
      { name: 'row', label: 'Fila', type: 'select', options: opt(['first', 'Primera'], ['second', 'Segunda']), list: true },
      { name: 'link', label: 'Enlace', type: 'text' },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0, list: true },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
    ] },
  { key: 'faq_categories', table: 'faq_categories', perm: 'faq_category', group: 'Contenido', label: 'Preguntas frecuentes', icon: '❓',
    labelSql: 'title', search: ['title', 'key'], sort: 'sort_order', children: 'faqs',
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true, list: true },
      { name: 'key', label: 'Clave', type: 'text', list: true },
      { name: 'audience', label: 'Para', type: 'select', options: AUDIENCE, list: true },
      { name: 'icon', label: 'Icono', type: 'text', list: true },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0, list: true },
      { name: 'active', label: 'Activa', type: 'bool', default: 1, list: true },
    ] },
  { key: 'faqs', table: 'faqs', perm: 'faq_category', group: 'Contenido', label: 'Preguntas', icon: '💬', hidden: true,
    labelSql: 'question', search: ['question'], sort: 'sort_order', filters: ['category_id'],
    fields: [
      { name: 'category_id', label: 'Categoría', type: 'ref', ref: 'faq_categories', required: true, list: true },
      { name: 'question', label: 'Pregunta', type: 'text', required: true, list: true },
      { name: 'answer', label: 'Respuesta', type: 'textarea', required: true },
      { name: 'sort_order', label: 'Orden', type: 'number', default: 0, list: true },
      { name: 'active', label: 'Activa', type: 'bool', default: 1, list: true },
    ] },
  { key: 'languages', table: 'languages', perm: 'language', group: 'Configuración', label: 'Idiomas', icon: '🌐',
    labelSql: 'name', search: ['name', 'code'],
    fields: [
      { name: 'image', label: 'Bandera', type: 'image', list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'name_en', label: 'Nombre (en inglés)', type: 'text', list: true },
      { name: 'code', label: 'Código', type: 'text', required: true, list: true },
      { name: 'country_code', label: 'País', type: 'text', list: true },
      { name: 'rtl', label: 'Derecha a izquierda', type: 'bool', list: true },
      { name: 'active', label: 'Activo', type: 'bool', default: 1, list: true },
      { name: 'is_default', label: 'Por defecto', type: 'bool', list: true },
    ] },

  // ── Administración ─────────────────────────────────────────────────────────
  { key: 'admin_users', table: 'admin_users', perm: 'admin_users', group: 'Administración', label: 'Usuarios administradores', icon: '🛡️',
    labelSql: 'name', search: ['name', 'email'], sort: 'name',
    fields: [
      { name: 'avatar', label: 'Avatar', type: 'image', list: true },
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'email', label: 'Email', type: 'email', required: true, list: true },
      { name: 'phone', label: 'Teléfono', type: 'phone', list: true },
      { name: 'password', label: 'Contraseña', type: 'password', help: 'Déjala vacía para no cambiarla' },
      { name: 'role_id', label: 'Rol', type: 'ref', ref: 'roles', required: true, list: true },
      { name: 'status', label: 'Estado', type: 'select', options: STATUS_ACTIVE, default: 'active', list: true },
    ] },
  { key: 'roles', table: 'roles', perm: 'roles', group: 'Administración', label: 'Roles', icon: '👥',
    labelSql: 'name', search: ['name'], sort: 'name',
    fields: [
      { name: 'name', label: 'Nombre', type: 'text', required: true, list: true },
      { name: 'description', label: 'Descripción', type: 'text', list: true },
      { name: 'permissions', label: 'Permisos', type: 'permissions', list: true },
    ] },
  { key: 'permissions', table: 'permissions', perm: 'permissions', group: 'Administración', label: 'Permisos', icon: '🔑',
    labelSql: 'name', search: ['name', 'module'], sort: 'module, id',
    fields: [
      { name: 'name', label: 'Permiso', type: 'text', required: true, list: true, help: 'módulo.acción, p. ej. booking.view' },
      { name: 'module', label: 'Módulo', type: 'text', required: true, list: true },
      { name: 'action', label: 'Acción', type: 'select', options: opt(['view', 'Ver'], ['create', 'Crear'], ['edit', 'Editar'], ['delete', 'Borrar']), required: true, list: true },
      { name: 'roles_count', label: 'Roles', type: 'readonly', virtual: true, list: true },
    ] },
];

const byKey = Object.fromEntries(R.map(r => [r.key, r]));
module.exports = { RESOURCES: R, byKey };
